### PR TITLE
Import debian version 1.0.2-2.

### PR DESCRIPTION
**Pull request by UTsweetyfish**
Related: https://github.com/docker/cli/pull/3746#issuecomment-1220624377
Upstream: https://github.com/modern-go/reflect2/commit/835802817d782825522f9d3fb740b00139f42e21

### CODE REVIEW

**Comment by Zeno-sole** [comment]
https://build.deepin.com/package/show/deepin:CI:deepin-community:golang-github-modern-go-reflect2:PR-1/golang-github-modern-go-reflect2   patch打失败了

**Comment by Zeno-sole** [comment]
@UTsweetyfish 你这个patch没有 pop出来

**Comment by UTsweetyfish** [comment]
> @UTsweetyfish 你这个patch没有 pop出来

哦刚看到（

**Comment by UTsweetyfish** [comment]
好了

**Comment by Zeno-sole** [comment]
/+1

**Pull request merged**
